### ISSUE TITLE
bug NPE

### ISSUE THREAD

**Issue by mbsimonovic** [meringlab/paxdb-search#1]
the service started throwing NPEs for any search. remove & add docker container fixed it.

```
<h3>Caused by:</h3><pre>java.lang.NullPointerException
    at org.apache.lucene.queryParser.QueryParser.jj_add_error_token(QueryParser.java:1801)
    at org.apache.lucene.queryParser.QueryParser.jj_scan_token(QueryParser.java:1750)
    at org.apache.lucene.queryParser.QueryParser.jj_3R_2(QueryParser.java:1638)
    at org.apache.lucene.queryParser.QueryParser.jj_3_1(QueryParser.java:1624)
    at org.apache.lucene.queryParser.QueryParser.jj_2_1(QueryParser.java:1616)
    at org.apache.lucene.queryParser.QueryParser.Clause(QueryParser.java:1289)
    at org.apache.lucene.queryParser.QueryParser.Query(QueryParser.java:1245)
    at org.apache.lucene.queryParser.QueryParser.TopLevelQuery(QueryParser.java:1234)
    at org.apache.lucene.queryParser.QueryParser.parse(QueryParser.java:206)
    at org.string_db.analysis.IndexConfig$ProteinQueryParserImpl.parse(IndexConfig.java:236)
    at org.string_db.analysis.IndexConfig$ProteinQueryParserImpl.parse(IndexConfig.java:224)
    at org.string_db.search.ProteinSearcher.search(ProteinSearcher.java:97)
    at org.string_db.search.ProteinSearcher.search(ProteinSearcher.java:80)
    at org.pax_db.api.rest.search.SearchResourceRepository.search(SearchResourceRepository.java:30)

```

**Comment by mbsimonovic** [comment]
it's better to let it fail fast and not catch these exceptions so docker would restart the container. this way it just hangs and keeps throwing exceptions
